import {
  LayoutDashboard,
  CalendarDays,
  ClipboardList,
  Users,
  Ticket,
  QrCode,
  BarChart3,
  Megaphone,
  Compass,
  MessagesSquare,
  Presentation,
  Settings,
  LayoutTemplate,
  UserCheck,
  FileText,
  Clock,
  ListChecks,
  Percent,
  CreditCard,
  TrendingUp,
  Layers,
  Newspaper,
  Bell,
  Mic,
  Handshake,
  Video,
  ShieldCheck,
  Plug,
  Webhook,
  Palette,
  Lock,
  Gauge,
  DollarSign,
  LayoutGrid,
  Zap,
  CalendarPlus,
  Image as ImageIcon,
  MapPin,
  Eye,
  Repeat,
  Copy,
  Link2,
  UserCog,
  Globe,
  SquarePen,
  CalendarCheck,
  Code,
  Map,
  Share2,
  Languages,
  UserPlus,
  Accessibility,
  KeyRound,
  GitBranch,
  CalendarClock,
  Sparkles,
  Gift,
  ArrowUp,
  BadgeCheck,
  Download,
  BookUser,
  Tags,
  Merge,
  UserX,
  ShieldAlert,
  History,
  Contact,
  Plus,
  Heart,
  ShoppingCart,
  Receipt,
  RotateCcw,
  Calculator,
  ArrowLeftRight,
  Wallet,
  ShoppingBag,
  Package,
  ScanLine,
  DoorOpen,
  CloudOff,
  Monitor,
  Printer,
  Radio,
  Cpu,
  Search,
  Mail,
  Filter,
  PieChart,
  MessageSquare,
  MessageCircle,
  Send,
  Workflow,
  FlaskConical,
  MailX,
  Tag,
  BellRing,
  Store,
  Star,
  Flame,
  ThumbsUp,
  Bookmark,
  Network,
  Music,
  Vote,
  HelpCircle,
  Trophy,
  Clapperboard,
  SlidersHorizontal,
  MonitorPlay,
  MonitorUp,
  Building2,
  Plane,
  Smartphone,
  Award,
  CirclePlay,
  Captions,
  Brush,
  LifeBuoy,
  ScrollText,
  Fingerprint,
  Database,
  Scale,
  Activity,
} from "lucide-react";

// Sidebar navigation for Geiger Events.
// Top-level items map to the Feature Taxonomy parent areas in
// docs/competitive-feature-matrix.md. Every feature for an area is listed as a
// sub-item so the full scope is visible in the UI.
export const workspaceNav = [
  {
    title: "Overview",
    icon: LayoutDashboard,
  },

  {
    // Per-event features (cover media, tickets, visibility, sharing, etc.) live
    // as tabs inside the Event editor — opened by selecting an event in
    // All Events — so only workspace-level destinations appear here.
    title: "Events",
    icon: CalendarDays,
    subItems: [
      { title: "All Events", icon: CalendarDays },
      { title: "Templates", icon: LayoutTemplate },
      { title: "Event Series", icon: Layers },
    ],
  },

  {
    title: "Registrations",
    icon: ClipboardList,
    subItems: [
      { title: "RSVPs", icon: UserCheck },
      { title: "Registration Forms", icon: FileText },
      { title: "Waitlist", icon: Clock },
      { title: "Approval Gates", icon: ShieldCheck },
      { title: "Capacity Limits", icon: Gauge },
      { title: "Plus-ones", icon: UserPlus },
      { title: "Dietary & Accessibility", icon: Accessibility },
      { title: "Token-gated", icon: Lock },
      { title: "Member-only", icon: KeyRound },
      { title: "Conditional Questions", icon: GitBranch },
      { title: "Group Registration", icon: Users },
      { title: "Registration Deadlines", icon: CalendarClock },
      { title: "Autofill Returning", icon: Sparkles },
      { title: "Register on Behalf", icon: Gift },
      { title: "Waitlist Auto-promotion", icon: ArrowUp },
      { title: "Confirmation Page", icon: BadgeCheck },
    ],
  },

  {
    title: "Guests",
    icon: Users,
    subItems: [
      { title: "Guest List", icon: Users },
      { title: "Segments", icon: ListChecks },
      { title: "Guest Import", icon: UserPlus },
      { title: "Who's Going", icon: Eye },
      { title: "Consent Tracking", icon: ShieldCheck },
      { title: "Attendee Export", icon: Download },
      { title: "Contact Book", icon: BookUser },
      { title: "Guest Profiles", icon: Contact },
      { title: "Tags & Notes", icon: Tags },
      { title: "Dedupe & Merge", icon: Merge },
      { title: "Blocklist", icon: UserX },
      { title: "Data Requests", icon: ShieldAlert },
      { title: "Communication History", icon: History },
    ],
  },

  {
    title: "Tickets",
    icon: Ticket,
    subItems: [
      { title: "Ticket Types", icon: Ticket },
      { title: "Coupons", icon: Percent },
      { title: "Payouts", icon: CreditCard },
      { title: "Ticket Tiers", icon: Tags },
      { title: "Early-bird Sales", icon: CalendarClock },
      { title: "Add-ons", icon: Plus },
      { title: "Donations", icon: Heart },
      { title: "Group Purchasing", icon: ShoppingCart },
      { title: "Taxes", icon: Receipt },
      { title: "Refunds", icon: RotateCcw },
      { title: "Payment Plans", icon: Calculator },
      { title: "Transfers", icon: ArrowLeftRight },
      { title: "Reserved Seating", icon: LayoutGrid },
      { title: "Dynamic Pricing", icon: TrendingUp },
      { title: "Anti-scalping & Resale", icon: ShieldCheck },
      { title: "Multi-currency", icon: DollarSign },
      { title: "Payment Methods", icon: Wallet },
      { title: "Invoices & Receipts", icon: FileText },
      { title: "Order Management", icon: ShoppingBag },
      { title: "Access-code Tickets", icon: KeyRound },
      { title: "Memberships", icon: BadgeCheck },
      { title: "Affiliate Codes", icon: Share2 },
      { title: "Bundles", icon: Package },
    ],
  },

  {
    title: "Check-in",
    icon: QrCode,
    subItems: [
      { title: "QR Tickets", icon: QrCode },
      { title: "Wallet Passes", icon: Wallet },
      { title: "Check-in App", icon: ScanLine },
      { title: "Door Sales", icon: DoorOpen },
      { title: "Offline Check-in", icon: CloudOff },
      { title: "Kiosk Mode", icon: Monitor },
      { title: "Badge Printing", icon: Printer },
      { title: "Session Check-in", icon: Clock },
      { title: "Capacity Control", icon: Gauge },
      { title: "RFID / NFC", icon: Radio },
      { title: "Smart Badges", icon: Cpu },
      { title: "Self Check-in", icon: UserCheck },
      { title: "Multi-gate & Zones", icon: Map },
      { title: "Real-time Attendance", icon: Activity },
      { title: "Staff Scanning Roles", icon: Users },
      { title: "Lead Retrieval", icon: Contact },
      { title: "Name-search Lookup", icon: Search },
    ],
  },

  {
    title: "Analytics",
    icon: BarChart3,
    subItems: [
      { title: "Sales", icon: TrendingUp },
      { title: "Attendance", icon: UserCheck },
      { title: "Cross-event Reporting", icon: Layers },
      { title: "Traffic & Sources", icon: Activity },
      { title: "Email Performance", icon: Mail },
      { title: "Engagement", icon: Sparkles },
      { title: "Sponsor ROI", icon: Handshake },
      { title: "Real-time Dashboards", icon: Gauge },
      { title: "Custom Report Builder", icon: FileText },
      { title: "Scheduled Reports", icon: CalendarClock },
      { title: "UTM Attribution", icon: Link2 },
      { title: "Conversion Funnels", icon: Filter },
      { title: "Revenue Forecasting", icon: TrendingUp },
      { title: "Surveys & NPS", icon: ClipboardList },
      { title: "Demographics", icon: PieChart },
    ],
  },

  {
    title: "Campaigns",
    icon: Megaphone,
    subItems: [
      { title: "Newsletters", icon: Newspaper },
      { title: "Automated Reminders", icon: Bell },
      { title: "Email Invites", icon: Mail },
      { title: "SMS Invites", icon: MessageSquare },
      { title: "WhatsApp Invites", icon: MessageCircle },
      { title: "Text Blasts", icon: Send },
      { title: "Segmentation", icon: ListChecks },
      { title: "Email Template Builder", icon: LayoutTemplate },
      { title: "Drip Sequences", icon: Workflow },
      { title: "A/B Testing", icon: FlaskConical },
      { title: "Send Scheduling", icon: Clock },
      { title: "Deliverability", icon: MailX },
      { title: "Personalization", icon: Tag },
      { title: "Push Notifications", icon: BellRing },
    ],
  },

  {
    title: "Discovery",
    icon: Compass,
    subItems: [
      { title: "Marketplace Listing", icon: Store },
      { title: "City & Category Search", icon: Search },
      { title: "Recommendations", icon: Sparkles },
      { title: "SEO Pages", icon: Globe },
      { title: "Organizer Profile", icon: UserCog },
      { title: "Follow Organizers", icon: Star },
      { title: "Social Proof", icon: Share2 },
      { title: "Featured Events", icon: Flame },
      { title: "External Distribution", icon: Send },
      { title: "Ratings & Reviews", icon: ThumbsUp },
      { title: "Saved & Wishlist", icon: Bookmark },
      { title: "Paid Promotion", icon: Megaphone },
      { title: "Partner Syndication", icon: Network },
      { title: "Referral Links", icon: Link2 },
      { title: "Embeddable Lists", icon: Code },
    ],
  },

  {
    title: "Community",
    icon: MessagesSquare,
    subItems: [
      { title: "Activity Feed", icon: Activity },
      { title: "Event Chat", icon: MessageSquare },
      { title: "Attendee Profiles", icon: Users },
      { title: "Photo Album", icon: ImageIcon },
      { title: "Shared Playlist", icon: Music },
      { title: "Polls", icon: Vote },
      { title: "Q&A", icon: HelpCircle },
      { title: "AI Matchmaking", icon: Sparkles },
      { title: "Visible Attendee List", icon: Eye },
      { title: "Mutual Connections", icon: Share2 },
      { title: "Meeting Scheduler", icon: CalendarClock },
      { title: "Direct Messaging", icon: Send },
      { title: "Live Reactions", icon: Heart },
      { title: "Moderation Tools", icon: ShieldCheck },
      { title: "Announcements", icon: Megaphone },
      { title: "Gamification", icon: Trophy },
      { title: "Discussion Boards", icon: MessageCircle },
    ],
  },

  {
    title: "Conference",
    icon: Presentation,
    subItems: [
      { title: "Agenda Builder", icon: ClipboardList },
      { title: "Speakers", icon: Mic },
      { title: "Sponsors", icon: Handshake },
      { title: "Recordings & Replay", icon: Video },
      { title: "Multi-track Sessions", icon: Layers },
      { title: "Speaker Backstage", icon: Clapperboard },
      { title: "Producer Controls", icon: SlidersHorizontal },
      { title: "Livestream Rooms", icon: Radio },
      { title: "Webinar Rooms", icon: MonitorPlay },
      { title: "Screen Sharing", icon: MonitorUp },
      { title: "Breakout Rooms", icon: Network },
      { title: "Expo Booths", icon: Store },
      { title: "Sponsor Rooms", icon: Building2 },
      { title: "Attendee Networking", icon: Users },
      { title: "Session Access Control", icon: Lock },
      { title: "Lead Capture", icon: ScanLine },
      { title: "Exhibitor QR Scanning", icon: QrCode },
      { title: "Venue Sourcing", icon: MapPin },
      { title: "Housing & Travel", icon: Plane },
      { title: "Call for Papers", icon: FileText },
      { title: "Speaker Portal", icon: Contact },
      { title: "Sponsorship Packages", icon: Package },
      { title: "Floor Plan & Booths", icon: LayoutGrid },
      { title: "My Agenda", icon: CalendarCheck },
      { title: "Mobile Event App", icon: Smartphone },
      { title: "CEU & Certificates", icon: Award },
      { title: "Simulive & On-demand", icon: CirclePlay },
      { title: "Captions & Transcription", icon: Captions },
      { title: "Gamification Passport", icon: Trophy },
    ],
  },

  {
    title: "Settings",
    icon: Settings,
    subItems: [
      { title: "Team & Members", icon: Users },
      { title: "Roles & Permissions", icon: ShieldCheck },
      { title: "Integrations", icon: Plug },
      { title: "API & Webhooks", icon: Webhook },
      { title: "Branding", icon: Palette },
      { title: "Security", icon: Lock },
      { title: "Billing & Plans", icon: CreditCard },
      { title: "Multi-event Dashboard", icon: LayoutGrid },
      { title: "SSO", icon: KeyRound },
      { title: "White-label", icon: Brush },
      { title: "Support & SLA", icon: LifeBuoy },
      { title: "Audit Logs", icon: ScrollText },
      { title: "2FA / MFA", icon: Fingerprint },
      { title: "Custom Domains", icon: Globe },
      { title: "Sub-accounts", icon: Building2 },
      { title: "Data & Backup", icon: Database },
      { title: "Sending Domains", icon: Mail },
      { title: "App Marketplace", icon: Store },
      { title: "Accessibility", icon: Accessibility },
      { title: "Localization", icon: Languages },
      { title: "Tax & Legal", icon: Scale },
    ],
  },
];
