-- Adopt @geiger/rbac
--
-- Storage for the suite authorization engine, plus a backfill from this app's
-- existing events.roles / events.project_members overlay.
--
-- Owns:
--   public.roles                    shared role definitions (suite-wide)
--   events.role_grants              this product's assignments
--   public.rbac_key_matches(...)    wildcard matching, mirrors @geiger/rbac keys.js
--   events.rbac_allows(...)         the predicate RLS policies call
--   events.rbac_migrate_key(text)   one-shot key translation for the backfill
--
-- The storage half is generated by @geiger/rbac's migrationSql("events") — do
-- not hand-edit it; regenerate from the package if the format changes.
--
-- NOTE ON ENFORCEMENT. This migration only creates and populates the
-- authorization tables. It does NOT replace any product table's `using (true)`
-- demo policy — flipping those is a separate, deliberate migration per table,
-- because a missing grant becomes a blank screen rather than a hidden button
-- the moment it lands.

-- @up
create extension if not exists pgcrypto;
create schema if not exists events;
grant usage on schema events to anon, authenticated, service_role;

-- Shared updated_at trigger for the authorization tables. Declared here (rather
-- than depending on a product's own touch_updated_at) so this block stands alone
-- whichever product runs it first.
create or replace function public.rbac_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Wildcard permission matching. Mirrors keys.js: "*" matches everything,
-- "<product>.*" and "<product>.<resource>.*" match by prefix, anything else is
-- an exact match. Immutable so it can be used in an index if that day comes.
create or replace function public.rbac_key_matches(p_patterns text[], p_key text)
returns boolean
language sql
immutable
as $$
  select exists (
    select 1
    from unnest(coalesce(p_patterns, '{}'::text[])) as pat
    where pat = '*'
       or pat = p_key
       or (
         right(pat, 2) = '.*'
         and left(p_key, length(pat) - 1) = left(pat, length(pat) - 1)
       )
  );
$$;

-- Shared role definitions. project_id scopes a role to one workspace; a null
-- project_id is a suite-wide template. permissions[] holds keys and wildcard
-- patterns spanning every product (events.order.refund, flow.issue.close, "*").
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  key text,
  name text not null default 'Untitled role',
  description text not null default '',
  color text not null default 'slate',
  permissions text[] not null default '{}',
  is_system boolean not null default false,
  sort integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.roles add column if not exists key text;
alter table public.roles add column if not exists permissions text[] not null default '{}';
alter table public.roles add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.roles add column if not exists deleted_at timestamptz;

create index if not exists roles_project_idx
  on public.roles (project_id) where deleted_at is null;
create unique index if not exists roles_project_key_uniq
  on public.roles (project_id, key) where key is not null and deleted_at is null;

drop trigger if exists roles_touch_updated_at on public.roles;
create trigger roles_touch_updated_at
before update on public.roles
for each row execute function public.rbac_touch_updated_at();

-- Per-product assignment. One row per (user, role) in a project. scope narrows
-- the grant to specific resources: {"event": ["<uuid>", ...]}. An empty scope
-- means the grant applies everywhere in the project.
create table if not exists events.role_grants (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid not null,
  role_id uuid not null references public.roles(id) on delete cascade,
  scope jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  granted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table events.role_grants add column if not exists scope jsonb not null default '{}'::jsonb;
alter table events.role_grants add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table events.role_grants add column if not exists deleted_at timestamptz;

-- The lookup rbac_allows() makes on every row of every gated query.
create index if not exists events_role_grants_lookup_idx
  on events.role_grants (user_id, project_id) where deleted_at is null;
create index if not exists events_role_grants_role_idx
  on events.role_grants (role_id) where deleted_at is null;
create unique index if not exists events_role_grants_uniq
  on events.role_grants (project_id, user_id, role_id) where deleted_at is null;

drop trigger if exists role_grants_touch_updated_at on events.role_grants;
create trigger role_grants_touch_updated_at
before update on events.role_grants
for each row execute function public.rbac_touch_updated_at();

-- The predicate every gated policy calls.
--
-- SECURITY DEFINER so a user can be authorized by grant rows they cannot
-- themselves select — otherwise the grants table's own RLS would have to be
-- open for authorization to work at all. STABLE so Postgres may cache it within
-- a statement rather than re-running it per row.
--
-- p_scope_type null  -> the permission is unscopeable; grants apply everywhere.
-- grant has no entry for p_scope_type -> that grant is unscoped. (Absence is
-- "no restriction", matching scope.js.)
create or replace function events.rbac_allows(
  p_permission text,
  p_project uuid default null,
  p_scope_type text default null,
  p_scope_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public, events
as $$
  select exists (
    select 1
    from events.role_grants g
    join public.roles r on r.id = g.role_id
    where g.user_id = auth.uid()
      and g.status = 'active'
      and g.deleted_at is null
      and r.deleted_at is null
      and (p_project is null or g.project_id = p_project)
      and public.rbac_key_matches(r.permissions, p_permission)
      and (
        p_scope_type is null
        or not jsonb_exists(g.scope, p_scope_type)
        or (
          p_scope_id is not null
          and jsonb_exists(g.scope -> p_scope_type, p_scope_id::text)
        )
      )
  );
$$;

grant execute on function events.rbac_allows(text, uuid, text, uuid) to anon, authenticated;
grant execute on function public.rbac_key_matches(text[], text) to anon, authenticated;

alter table public.roles enable row level security;
alter table events.role_grants enable row level security;

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists roles_write on public.roles;
create policy roles_write on public.roles
  for all to authenticated using (true) with check (true);

drop policy if exists role_grants_read on events.role_grants;
create policy role_grants_read on events.role_grants
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists role_grants_write on events.role_grants;
create policy role_grants_write on events.role_grants
  for all to authenticated using (true) with check (true);

-- ---------------------------------------------------------------------------
-- Backfill from the pre-package overlay.
-- ---------------------------------------------------------------------------

-- Old catalog keys were nav-shaped (view.orders, team.invite). Translate them
-- into <product>.<resource>.<action>. Anything unrecognised maps to null and is
-- dropped — an unknown key could never have matched a catalog entry anyway.
create or replace function events.rbac_migrate_key(p_key text)
returns text
language sql
immutable
as $$
  select case
    when p_key = 'roles.manage'      then 'events.role.manage'
    when p_key = 'team.invite'       then 'events.team.invite'
    when p_key = 'team.assign_roles' then 'events.team.assign'
    when p_key = 'billing.manage'    then 'events.billing.manage'
    when p_key = 'settings.manage'   then 'events.settings.manage'
    when p_key like 'view.%'         then 'events.' || substr(p_key, 6) || '.view'
    else null
  end;
$$;

-- Existing role definitions keep their id, so any project_members row already
-- pointing at one still resolves after the move.
--
-- Deduplicated on (project, key) first: the old ensureSystemRoles() only skipped
-- seeding when a project had NO roles at all, so a project could accumulate two
-- "owner" rows — which public.roles.roles_project_key_uniq rightly refuses.
-- The earliest row wins; later duplicates are dropped rather than renamed,
-- because grants point at role ids and the oldest is the one members hold.
-- Rows with no key are all kept (they are distinct by id).
insert into public.roles (
  id, project_id, key, name, description, color,
  permissions, is_system, sort, metadata, created_by, created_at
)
select
  r.id,
  r.project_id,
  nullif(r.metadata ->> 'key', ''),
  r.name,
  r.description,
  r.color,
  -- Owner becomes the wildcard rather than a frozen list, so it keeps granting
  -- new permissions as the catalog grows.
  case
    when coalesce(r.metadata ->> 'key', '') = 'owner' then array['*']
    else coalesce(
      (
        select array_agg(distinct s.m)
        from (select events.rbac_migrate_key(p) as m from unnest(r.permissions) as p) s
        where s.m is not null
      ),
      '{}'::text[]
    )
  end,
  r.is_system,
  r.sort,
  r.metadata,
  r.created_by,
  r.created_at
from (
  select distinct on (
    d.project_id,
    coalesce(nullif(d.metadata ->> 'key', ''), d.id::text)
  ) d.*
  from events.roles d
  where d.deleted_at is null
  order by
    d.project_id,
    coalesce(nullif(d.metadata ->> 'key', ''), d.id::text),
    d.created_at asc,
    d.id asc
) r
on conflict (id) do nothing;

-- Every project gets an Owner role. Only Owner is seeded here: its permission
-- list is the stable wildcard, whereas the other system roles are defined in
-- geiger-rbac.config.js and are seeded by the app (ensureSystemRoles) so the
-- catalog stays the single source of truth for them.
insert into public.roles (project_id, key, name, description, color, permissions, is_system, sort)
select p.id, 'owner', 'Owner',
       'Full access to everything, including billing.', 'violet',
       array['*'], true, 0
from public.projects p
where p.deleted_at is null
  and not exists (
    select 1 from public.roles r
    where r.project_id = p.id and r.key = 'owner' and r.deleted_at is null
  );

-- Assignments from the old overlay.
--
-- A member whose role_id was one of the duplicates dropped above is remapped to
-- the surviving role with the same key, so deduplication never costs anyone
-- their access. Only a member pointing at a role that no longer exists in any
-- form is skipped.
insert into events.role_grants (project_id, user_id, role_id, status, granted_by, created_at)
select
  m.project_id,
  m.user_id,
  coalesce(pr.id, alt.id),
  case when m.status = 'active' then 'active' else 'inactive' end,
  m.invited_by,
  coalesce(m.joined_at, m.created_at)
from events.project_members m
left join public.roles pr
  on pr.id = m.role_id and pr.deleted_at is null
left join events.roles er
  on er.id = m.role_id
left join public.roles alt
  on alt.project_id = m.project_id
 and alt.key = nullif(er.metadata ->> 'key', '')
 and alt.deleted_at is null
where m.deleted_at is null
  and m.user_id is not null
  and m.role_id is not null
  and coalesce(pr.id, alt.id) is not null
on conflict (project_id, user_id, role_id) where deleted_at is null do nothing;

-- The project's creator is its Owner. This is what "the project owner can set
-- all things" means, and it guarantees every project has at least one account
-- that can administer roles once enforcement is switched on.
insert into events.role_grants (project_id, user_id, role_id, status)
select p.id, p.created_by, r.id, 'active'
from public.projects p
join public.roles r
  on r.project_id = p.id and r.key = 'owner' and r.deleted_at is null
where p.deleted_at is null
  and p.created_by is not null
on conflict (project_id, user_id, role_id) where deleted_at is null do nothing;

-- @down
drop function if exists events.rbac_migrate_key(text);

drop policy if exists role_grants_read on events.role_grants;
drop policy if exists role_grants_write on events.role_grants;
drop function if exists events.rbac_allows(text, uuid, text, uuid);
drop table if exists events.role_grants cascade;

-- public.roles, public.rbac_key_matches and public.rbac_touch_updated_at are
-- shared across the suite and are intentionally left in place — dropping them
-- would delete another product's role definitions. Backfilled rows are left
-- too; events.roles still holds the originals.
